version: "3.8"

x-environment: &env
  env_file: .env

x-django: &django
  <<: *env
  build: .
#  environment:
#    DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  restart: unless-stopped

services:
  django:
    <<: *django
    command: ./run/gunicorn.sh
    healthcheck:
      test: "curl --fail http://0.0.0.0:${DJANGO_PORT}/health/ || exit 1"
      retries: 3
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"

#  db:
#    image: postgres:14
#    restart: unless-stopped
#    env_file:
#      - .env
#    ports:
#      - "127.0.0.1:5432:5432"
#    volumes:
#      - postgresql:/var/lib/postgresql

#volumes:
#  postgresql:
#    driver: local